/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as MarketingAiRouteImport } from './routes/marketing-ai'
import { Route as MarketingDashboardRouteImport } from './routes/marketing-dashboard'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as SalesEngineRouteImport } from './routes/sales-engine'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ApiAdminBufferRouteImport } from './routes/api/admin/buffer'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminManageRouteImport } from './routes/api/admin/manage'
import { Route as ApiPublicCapturarLeadSiteRouteImport } from './routes/api/public/capturar-lead-site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAiRoute = MarketingAiRouteImport.update({
  id: '/marketing-ai',
  path: '/marketing-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingDashboardRoute = MarketingDashboardRouteImport.update({
  id: '/marketing-dashboard',
  path: '/marketing-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEngineRoute = SalesEngineRouteImport.update({
  id: '/sales-engine',
  path: '/sales-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBufferRoute = ApiAdminBufferRouteImport.update({
  id: '/api/admin/buffer',
  path: '/api/admin/buffer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminManageRoute = ApiAdminManageRouteImport.update({
  id: '/api/admin/manage',
  path: '/api/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCapturarLeadSiteRoute =
  ApiPublicCapturarLeadSiteRouteImport.update({
    id: '/api/public/capturar-lead-site',
    path: '/api/public/capturar-lead-site',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/marketing-ai': typeof MarketingAiRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/precos': typeof PrecosRoute
  '/sales-engine': typeof SalesEngineRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/admin/buffer': typeof ApiAdminBufferRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/manage': typeof ApiAdminManageRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/marketing-ai': typeof MarketingAiRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/precos': typeof PrecosRoute
  '/sales-engine': typeof SalesEngineRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/admin/buffer': typeof ApiAdminBufferRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/manage': typeof ApiAdminManageRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/marketing-ai': typeof MarketingAiRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/precos': typeof PrecosRoute
  '/sales-engine': typeof SalesEngineRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/api/admin/buffer': typeof ApiAdminBufferRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/manage': typeof ApiAdminManageRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/marketing-ai'
    | '/marketing-dashboard'
    | '/precos'
    | '/sales-engine'
    | '/blog/$slug'
    | '/api/admin/buffer'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/manage'
    | '/api/public/capturar-lead-site'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/marketing-ai'
    | '/marketing-dashboard'
    | '/precos'
    | '/sales-engine'
    | '/blog/$slug'
    | '/api/admin/buffer'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/manage'
    | '/api/public/capturar-lead-site'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/marketing-ai'
    | '/marketing-dashboard'
    | '/precos'
    | '/sales-engine'
    | '/blog_/$slug'
    | '/api/admin/buffer'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/manage'
    | '/api/public/capturar-lead-site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  MarketingAiRoute: typeof MarketingAiRoute
  MarketingDashboardRoute: typeof MarketingDashboardRoute
  PrecosRoute: typeof PrecosRoute
  SalesEngineRoute: typeof SalesEngineRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiAdminBufferRoute: typeof ApiAdminBufferRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminManageRoute: typeof ApiAdminManageRoute
  ApiPublicCapturarLeadSiteRoute: typeof ApiPublicCapturarLeadSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-ai': {
      id: '/marketing-ai'
      path: '/marketing-ai'
      fullPath: '/marketing-ai'
      preLoaderRoute: typeof MarketingAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-dashboard': {
      id: '/marketing-dashboard'
      path: '/marketing-dashboard'
      fullPath: '/marketing-dashboard'
      preLoaderRoute: typeof MarketingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-engine': {
      id: '/sales-engine'
      path: '/sales-engine'
      fullPath: '/sales-engine'
      preLoaderRoute: typeof SalesEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/buffer': {
      id: '/api/admin/buffer'
      path: '/api/admin/buffer'
      fullPath: '/api/admin/buffer'
      preLoaderRoute: typeof ApiAdminBufferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/manage': {
      id: '/api/admin/manage'
      path: '/api/admin/manage'
      fullPath: '/api/admin/manage'
      preLoaderRoute: typeof ApiAdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capturar-lead-site': {
      id: '/api/public/capturar-lead-site'
      path: '/api/public/capturar-lead-site'
      fullPath: '/api/public/capturar-lead-site'
      preLoaderRoute: typeof ApiPublicCapturarLeadSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  MarketingAiRoute: MarketingAiRoute,
  MarketingDashboardRoute: MarketingDashboardRoute,
  PrecosRoute: PrecosRoute,
  SalesEngineRoute: SalesEngineRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiAdminBufferRoute: ApiAdminBufferRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminManageRoute: ApiAdminManageRoute,
  ApiPublicCapturarLeadSiteRoute: ApiPublicCapturarLeadSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
