/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is committed for the Lovable preview; route generation may overwrite it.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as MarketingAIRouteImport } from './routes/marketing-ai'
import { Route as SalesEngineRouteImport } from './routes/sales-engine'
import { Route as MarketingDashboardRouteImport } from './routes/marketing-dashboard'
import { Route as ApiPublicCapturarLeadSiteRouteImport } from './routes/api/public/capturar-lead-site'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const BlogRoute = BlogRouteImport.update({ id: '/blog', path: '/blog', getParentRoute: () => rootRouteImport } as any)
const PrecosRoute = PrecosRouteImport.update({ id: '/precos', path: '/precos', getParentRoute: () => rootRouteImport } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({ id: '/blog_/$slug', path: '/blog/$slug', getParentRoute: () => rootRouteImport } as any)
const MarketingAIRoute = MarketingAIRouteImport.update({ id: '/marketing-ai', path: '/marketing-ai', getParentRoute: () => rootRouteImport } as any)
const SalesEngineRoute = SalesEngineRouteImport.update({ id: '/sales-engine', path: '/sales-engine', getParentRoute: () => rootRouteImport } as any)
const MarketingDashboardRoute = MarketingDashboardRouteImport.update({ id: '/marketing-dashboard', path: '/marketing-dashboard', getParentRoute: () => rootRouteImport } as any)
const ApiPublicCapturarLeadSiteRoute = ApiPublicCapturarLeadSiteRouteImport.update({ id: '/api/public/capturar-lead-site', path: '/api/public/capturar-lead-site', getParentRoute: () => rootRouteImport } as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({ id: '/api/admin/login', path: '/api/admin/login', getParentRoute: () => rootRouteImport } as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({ id: '/api/admin/logout', path: '/api/admin/logout', getParentRoute: () => rootRouteImport } as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({ id: '/api/admin/dashboard', path: '/api/admin/dashboard', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketing-ai': typeof MarketingAIRoute
  '/sales-engine': typeof SalesEngineRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketing-ai': typeof MarketingAIRoute
  '/sales-engine': typeof SalesEngineRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/marketing-ai': typeof MarketingAIRoute
  '/sales-engine': typeof SalesEngineRoute
  '/marketing-dashboard': typeof MarketingDashboardRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/precos' | '/blog/$slug' | '/marketing-ai' | '/sales-engine' | '/marketing-dashboard' | '/api/public/capturar-lead-site' | '/api/admin/login' | '/api/admin/logout' | '/api/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/precos' | '/blog/$slug' | '/marketing-ai' | '/sales-engine' | '/marketing-dashboard' | '/api/public/capturar-lead-site' | '/api/admin/login' | '/api/admin/logout' | '/api/admin/dashboard'
  id: '__root__' | '/' | '/blog' | '/precos' | '/blog_/$slug' | '/marketing-ai' | '/sales-engine' | '/marketing-dashboard' | '/api/public/capturar-lead-site' | '/api/admin/login' | '/api/admin/logout' | '/api/admin/dashboard'
  fileRoutesById: FileRoutesById
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/blog': { id: '/blog'; path: '/blog'; fullPath: '/blog'; preLoaderRoute: typeof BlogRouteImport; parentRoute: typeof rootRouteImport }
    '/precos': { id: '/precos'; path: '/precos'; fullPath: '/precos'; preLoaderRoute: typeof PrecosRouteImport; parentRoute: typeof rootRouteImport }
    '/blog_/$slug': { id: '/blog_/$slug'; path: '/blog/$slug'; fullPath: '/blog/$slug'; preLoaderRoute: typeof BlogSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/marketing-ai': { id: '/marketing-ai'; path: '/marketing-ai'; fullPath: '/marketing-ai'; preLoaderRoute: typeof MarketingAIRouteImport; parentRoute: typeof rootRouteImport }
    '/sales-engine': { id: '/sales-engine'; path: '/sales-engine'; fullPath: '/sales-engine'; preLoaderRoute: typeof SalesEngineRouteImport; parentRoute: typeof rootRouteImport }
    '/marketing-dashboard': { id: '/marketing-dashboard'; path: '/marketing-dashboard'; fullPath: '/marketing-dashboard'; preLoaderRoute: typeof MarketingDashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/capturar-lead-site': { id: '/api/public/capturar-lead-site'; path: '/api/public/capturar-lead-site'; fullPath: '/api/public/capturar-lead-site'; preLoaderRoute: typeof ApiPublicCapturarLeadSiteRouteImport; parentRoute: typeof rootRouteImport }
    '/api/admin/login': { id: '/api/admin/login'; path: '/api/admin/login'; fullPath: '/api/admin/login'; preLoaderRoute: typeof ApiAdminLoginRouteImport; parentRoute: typeof rootRouteImport }
    '/api/admin/logout': { id: '/api/admin/logout'; path: '/api/admin/logout'; fullPath: '/api/admin/logout'; preLoaderRoute: typeof ApiAdminLogoutRouteImport; parentRoute: typeof rootRouteImport }
    '/api/admin/dashboard': { id: '/api/admin/dashboard'; path: '/api/admin/dashboard'; fullPath: '/api/admin/dashboard'; preLoaderRoute: typeof ApiAdminDashboardRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  BlogRoute,
  PrecosRoute,
  BlogSlugRoute,
  MarketingAIRoute,
  SalesEngineRoute,
  MarketingDashboardRoute,
  ApiPublicCapturarLeadSiteRoute,
  ApiAdminLoginRoute,
  ApiAdminLogoutRoute,
  ApiAdminDashboardRoute,
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  PrecosRoute: typeof PrecosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MarketingAIRoute: typeof MarketingAIRoute
  SalesEngineRoute: typeof SalesEngineRoute
  MarketingDashboardRoute: typeof MarketingDashboardRoute
  ApiPublicCapturarLeadSiteRoute: typeof ApiPublicCapturarLeadSiteRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
