/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ApiPublicCapturarLeadSiteRouteImport } from './routes/api/public/capturar-lead-site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCapturarLeadSiteRoute =
  ApiPublicCapturarLeadSiteRouteImport.update({
    id: '/api/public/capturar-lead-site',
    path: '/api/public/capturar-lead-site',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/precos': typeof PrecosRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/api/public/capturar-lead-site': typeof ApiPublicCapturarLeadSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/blog' | '/precos' | '/blog/$slug' | '/api/public/capturar-lead-site'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/blog' | '/precos' | '/blog/$slug' | '/api/public/capturar-lead-site'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/precos'
    | '/blog_/$slug'
    | '/api/public/capturar-lead-site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  PrecosRoute: typeof PrecosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiPublicCapturarLeadSiteRoute: typeof ApiPublicCapturarLeadSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capturar-lead-site': {
      id: '/api/public/capturar-lead-site'
      path: '/api/public/capturar-lead-site'
      fullPath: '/api/public/capturar-lead-site'
      preLoaderRoute: typeof ApiPublicCapturarLeadSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  PrecosRoute: PrecosRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiPublicCapturarLeadSiteRoute: ApiPublicCapturarLeadSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
